name: Terraform-Vagrant-Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform & Vagrant
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3   # يسحب الريبو (main.tf + playbook.yml + Vagrantfile)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: C:\Terraform\terraform.exe init

      - name: Terraform Apply (run Vagrant)
        run: C:\Terraform\terraform.exe apply -auto-approve

      - name: Save inventory file
        run: |
          echo "[ubuntu]" > inventory.ini
          echo "192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=$HOME/.vagrant.d/insecure_private_key" >> inventory.ini
        shell: pwsh

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory
          path: inventory.ini

  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v3

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: inventory

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
