name: Terraform-Vagrant-Ansible

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init & Apply
        run: |
          cd terraform-ansible-vbox
          terraform init
          terraform apply -auto-approve

      - name: Run Ansible
        run: |
          cd terraform-ansible-vbox
          ansible-playbook -i inventory.ini playbook.yml
