
name: Terraform-Vagrant-Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform & Vagrant
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3   # يسحب الريبو (main.tf + playbook.yml + Vagrantfile)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      

      - name: Terraform Init
        run: C:\Terraform\terraform.exe init

      - name: Terraform Apply (run Vagrant)
        run: C:\Terraform\terraform.exe apply -auto-approve

        # env:
        #  ROJECT_PATH: /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox

      - name: Generate inventory.ini
        run: |
           echo "[ubuntu]" > inventory.ini
           echo "127.0.0.1 ansible_user=vagrant ansible_port=2222 ansible_ssh_private_key_file=/mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/.vagrant/machines/default/virtualbox/private_key ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> inventory.ini
        shell: pwsh


  

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory
          path: inventory.ini

    

  ansible:
   name: Configure K8s & Deploy Nginx
   needs: terraform
   runs-on: self-hosted
   steps:
      - name: Checkout Code with LF Line Endings
        uses: actions/checkout@v3
        
 
      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: inventory

      - name: Prepare SSH key
        shell: pwsh
        run: |
            wsl --user root chmod 600 /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/.vagrant/machines/default/virtualbox/private_key 

       
        

      - name: Remove old SSH host key (root + houssam)
        shell: pwsh
        run: |
            wsl --user root ssh-keygen -f "/root/.ssh/known_hosts" -R "[127.0.0.1]:2222" || true
            wsl bash -c "ssh-keygen -f '/home/houssam/.ssh/known_hosts' -R '[127.0.0.1]:2222'" || true
        

    # 👇 NEW: Setup venv and install Ansible + k8s SDK
      - name: Setup Ansible Virtual Environment
        shell: pwsh
        run: |
           wsl bash -c "python3 -m venv ~/ansible-env && source ~/ansible-env/bin/activate && pip install --upgrade pip ansible kubernetes"
         

    # 👇 Run playbook INSIDE the venv
      - name: Run Ansible Playbook
        shell: pwsh
        run: |
          wsl bash -c "source ~/ansible-env/bin/activate && echo '⏳ Waiting 20 seconds...' && sleep 20 && ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/inventory.ini /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/playbook.yml"
        
