# name: Terraform-Vagrant-Ansible

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   terraform:
#     name: Terraform & Vagrant
#     runs-on: self-hosted

#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.7

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Apply (run Vagrant)
#         run: terraform apply -auto-approve

#       - name: Generate Ansible inventory
#         run: |
#           echo "[ubuntu]" > inventory.ini
#           echo "127.0.0.1 ansible_port=2222 ansible_user=vagrant ansible_ssh_private_key_file=$(pwd)/.vagrant/machines/default/virtualbox/private_key" >> inventory.ini

#       - name: Fix private key permissions
#         run: chmod 600 ./.vagrant/machines/default/virtualbox/private_key

#       - name: Upload inventory
#         uses: actions/upload-artifact@v4
#         with:
#           name: inventory
#           path: inventory.ini

#   ansible:
#     name: Run Ansible
#     runs-on: self-hosted
#     needs: terraform

#     steps:
#       - uses: actions/checkout@v3

#       - name: Download inventory
#         uses: actions/download-artifact@v4
#         with:
#           name: inventory

#       - name: Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install -y ansible

#       - name: Run Playbook
#         run: ansible-playbook -i inventory.ini playbook.yml

name: Terraform-Vagrant-Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform & Vagrant
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3   # يسحب الريبو (main.tf + playbook.yml + Vagrantfile)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      

      - name: Terraform Init
        run: C:\Terraform\terraform.exe init

      - name: Terraform Apply (run Vagrant)
        run: C:\Terraform\terraform.exe apply -auto-approve

      - name: Save inventory file
        run: |
          echo "[ubuntu]" > inventory.ini
          echo "127.0.0.1 ansible_user=vagrant ansible_ssh_private_key_file=$HOME/.vagrant.d/insecure_private_key" >> inventory.ini
        shell: pwsh

      # - name: Fix private key permissions
      #   shell: pwsh
      #   run: |
      #        wsl chmod 600 /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/.vagrant/machines/default/virtualbox/private_key
  

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory
          path: inventory.ini

      # - name: Fix private key permissions
      #   shell: pwsh
      #   run: |
      #        wsl chmod 600 /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/.vagrant/machines/default/virtualbox/private_key    

  ansible:
    name: Run Ansible
    runs-on: self-hosted
    needs: terraform

    steps:
      - uses: actions/checkout@v3

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: inventory

      # - name: Install Ansible
      #   shell: pwsh
      #   run: |
      #     wsl sudo apt update
      #     wsl sudo apt install -y ansible
      - name: Fix private key permissions
        shell: pwsh
        run: |
             wsl --user root
             wsl chmod 600 /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/.vagrant/machines/default/virtualbox/private_key 
             
      - name: remove the old key li ken ma5doum ken project 9able ken ye5dem
        shell: pwsh
        run: |
            wsl --user root
            wsl ssh-keygen -f "/root/.ssh/known_hosts" -R "[127.0.0.1]:2222"
  
      - name: Run Playbook
        shell: pwsh
        run: |
            wsl --user root
            wsl ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/inventory.ini /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/playbook.yml

            # wsl ansible-playbook -i /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/inventory.ini /mnt/c/Users/HOUSSAM/Desktop/terraform-ansible-vbox/playbook.yml
              # wsl ansible-playbook -i inventory.ini playbook.yml

